# Site settings
title: Internship Blog
author:
  name: Oğuzhan Altıntaş
  email: oguzhanaltintas684@gmail.com
description: "Blog of a college student about his internship"

# Build settings
remote_theme: jekyll/minima

minima: 
  skin: auto
  social_links: 
     - { platform: github,  user_url: "https://github.com/garibo684" }

url: "http://garibo684.github.io"

disqus:
  shortname: garibo684
