# Site settings
title: Internship Blog
author:
  name: Oğuzhan Altıntaş
  email: oguzhanaltintas684@gmail.com
description: "Blog of a college student about his internship"

# Build settings
remote_theme: garibo684/minima_test
